### ISSUE TITLE
QA - Website Builder - Grid Option is Overlapped on Textbox Option.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/website-builder#339] opened 2018-02-13 03:44 UTC
Create Project.
Create Multiple Partial in That Project.
Now Go to Project Setiing.
Apply Template 2 on that Project.
Now Go to Partials Folder.
Click on place Order Partial.
Now Click on Preview option of Header Setion.
Observe Result.

![grid option is overlapped on textbox option 1](https://user-images.githubusercontent.com/36226408/36132606-4d241fa4-109e-11e8-99b1-a97299304fb9.jpg)
![grid option is overlapped on textbox option 2](https://user-images.githubusercontent.com/36226408/36132607-4d5e9fa8-109e-11e8-9f18-142cd0faef5c.jpg)

**Comment by gkumar9** [comment] 2018-03-12 13:23
The issue is valid and checked inside http://grapesjs.com/ and found the same prob. But the preview icon given by grapes is not at all useful.

**Comment by qajha** [comment] 2018-03-13 05:12
As the mention comment by dev member I have closed this ticket

**Closed by qajha** 2018-03-13 05:12 UTC
Labels: Low, Move To QA
