### ISSUE TITLE
QA - Website Builder - Layout - Default Layout - File tab missing when click on main website option.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/website-builder#315] opened 2018-02-12 07:56 UTC
Create Project.
Click on default Layout.
Now click on main website option.
Observe File Tab Header is missing.

![file tab missing when user click on main website option](https://user-images.githubusercontent.com/36226408/36087752-ea74acb0-0ff9-11e8-9a7b-806201876569.jpg)

**Comment by Nikunj025** [comment] 2018-02-12 07:59
Create Project.
Click on default Layout.
Now click on main website option.
Observe File Tab Header is missing.

**Comment by fsaiyedOB** [comment] 2018-02-13 09:36
Only the editor and settings page are kept in tabs.

**Comment by acharotariya** [comment] 2018-02-19 06:27
Still Not resolved.

**Comment by fsaiyedOB** [comment] 2018-02-24 12:26
Only the editor pages are kept in tabs. Do not click on blank white space in tree nodes. Click on the text in tree nodes.

**Comment by qajha** [comment] 2018-02-25 07:11
We need to discuss with Mohit on Monday regarding this ticket

**Comment by gkumar9** [comment] 2018-04-04 07:03
Currently tabs have been not used, hence issue is invalid. Cant reproduce.

**Comment by qajha** [comment] 2018-04-04 07:17
I have close this Issue due to Tab functionality is remove from the website builder.

**Closed by qajha** 2018-04-04 07:17 UTC
Labels: Discussion, Future Enhancement, Low
