### ISSUE TITLE
QA - Website Builder - User Not able to close alert message and also page is not responding.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/website-builder#333] opened 2018-02-12 12:32 UTC
Create project.
apply any Template from Project Setting.
Now Open Multiple partial files.
Change only Tab without updating data.

![user not able to close alert message and also page is stucked](https://user-images.githubusercontent.com/36226408/36097009-f06bb22e-101e-11e8-8ef1-bd8afc30381b.jpg)

**Comment by fsaiyedOB** [comment] 2018-02-14 07:30
Reproduced the test case, no errors were found.

**Comment by fsaiyedOB** [comment] 2018-03-08 11:01
Tabs are removed for now.

**Comment by qajha** [comment] 2018-03-14 12:31
Due to Tab remove we have close this ticket

**Comment by qajha** [comment] 2018-03-15 02:17
closed Issue

**Closed by qajha** 2018-03-15 02:17 UTC
Labels: Low
